# Generated by Django 6.0.4 on 2026-04-23 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaInfantil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('idade_minima', models.PositiveSmallIntegerField(verbose_name='Idade minima')),
                ('idade_maxima', models.PositiveSmallIntegerField(verbose_name='Idade maxima')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Sala infantil',
                'verbose_name_plural': 'Salas infantis',
                'ordering': ['idade_minima', 'idade_maxima', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Crianca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('responsavel_nome', models.CharField(max_length=150, verbose_name='Responsavel')),
                ('responsavel_telefone', models.CharField(max_length=20, verbose_name='Telefone do responsavel')),
                ('observacoes_gerais', models.TextField(blank=True, verbose_name='Observacoes gerais')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('restricoes_alimentares', models.TextField(blank=True, verbose_name='Restricoes alimentares')),
                ('necessidades_especiais', models.TextField(blank=True, verbose_name='Necessidades especiais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criancas', to='infantil.salainfantil', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Crianca',
                'verbose_name_plural': 'Criancas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='AulaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema da aula')),
                ('texto_base', models.CharField(blank=True, max_length=200, verbose_name='Texto base')),
                ('conteudo_licao', models.TextField(blank=True, verbose_name='Conteudo da licao')),
                ('anexo_licao', models.FileField(blank=True, null=True, upload_to='infantil/licoes/', verbose_name='Anexo da licao')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='infantil.salainfantil', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Aula da sala',
                'verbose_name_plural': 'Aulas das salas',
                'ordering': ['-data', 'sala__nome'],
                'constraints': [models.UniqueConstraint(fields=('sala', 'data'), name='uniq_aula_por_sala_e_data')],
            },
        ),
        migrations.CreateModel(
            name='SalaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('lider_sala', 'Lider de sala'), ('professor', 'Professor'), ('auxiliar', 'Auxiliar'), ('apoio', 'Apoio')], default='auxiliar', max_length=20, verbose_name='Papel na sala')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_salas_infantis', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to='infantil.salainfantil', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Membro da sala',
                'verbose_name_plural': 'Membros da sala',
                'ordering': ['sala__nome', 'papel', 'membro__first_name', 'membro__username'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('membro', 'sala'), name='uniq_membro_ativo_por_sala')],
            },
        ),
    ]
