# Generated by Django 6.0.4 on 2026-04-24 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaResponsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficha', models.CharField(max_length=20, verbose_name='Numero da ficha')),
                ('observacao', models.TextField(blank=True, verbose_name='Observacao')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('exibido', 'Exibido'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('exibido_em', models.DateTimeField(blank=True, null=True, verbose_name='Exibido em')),
                ('resolvido_em', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chamadas_responsavel_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chamadas_responsavel', to='infantil.salainfantil', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Chamada de responsavel',
                'verbose_name_plural': 'Chamadas de responsavel',
                'ordering': ['status', '-criado_em'],
            },
        ),
    ]
