# Generated by Django 6.0.4 on 2026-04-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantil', '0002_chamadaresponsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamadaresponsavel',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelado em'),
        ),
        migrations.AddField(
            model_name='chamadaresponsavel',
            name='reenviado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reenviado em'),
        ),
    ]
