# Generated by Django 6.0.4 on 2026-04-24 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infantil', '0003_chamadaresponsavel_cancelado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='crianca',
            name='medicacao_ou_cuidado_especial',
            field=models.TextField(blank=True, verbose_name='Medicacao ou cuidado especial'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='observacao_para_professor',
            field=models.TextField(blank=True, verbose_name='Observacao para o professor'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='pode_comer_lanche_igreja',
            field=models.BooleanField(default=True, verbose_name='Pode comer lanche da igreja?'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='responsavel_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail do responsavel'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='responsavel_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='criancas_cadastradas', to=settings.AUTH_USER_MODEL, verbose_name='Responsavel usuario'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro')], max_length=20, verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='crianca',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('inativo', 'Inativo')], default='pendente', max_length=20, verbose_name='Status do cadastro'),
        ),
        migrations.AlterField(
            model_name='crianca',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='criancas', to='infantil.salainfantil', verbose_name='Sala'),
        ),
    ]
