# Generated by Django 6.0.4 on 2026-08-24 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0009_departmentrole_can_manage_schedules'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentScheduleRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade minima')),
                ('recommended_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantidade recomendada')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_requirements', to='departamentos.departamento', verbose_name='Departamento')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_requirements', to='departamentos.departmentrole', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Requisito de composicao de escala',
                'verbose_name_plural': 'Requisitos de composicao de escala',
                'ordering': ['department__nome', 'role__name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('department', 'role'), name='uniq_schedule_requirement_department_role'), models.CheckConstraint(condition=models.Q(('minimum_quantity__gte', 0)), name='schedule_requirement_minimum_non_negative'), models.CheckConstraint(condition=models.Q(('recommended_quantity__gte', 0)), name='schedule_requirement_recommended_non_negative'), models.CheckConstraint(condition=models.Q(('recommended_quantity__gte', models.F('minimum_quantity'))), name='schedule_requirement_recommended_gte_minimum')],
            },
        ),
    ]
