# Generated by Django 6.0.4 on 2026-05-01 11:10

import django.core.validators
import django.db.models.deletion
import ministros.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=160, verbose_name='Nome completo')),
                ('nome_ministerial', models.CharField(blank=True, max_length=160, verbose_name='Nome ministerial/publico')),
                ('tipo', models.CharField(choices=[('casa', 'Ministro da casa'), ('visitante', 'Ministro visitante')], default='visitante', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('atualizado', 'Atualizado')], default='pendente', max_length=20, verbose_name='Status do cadastro')),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='Telefone/WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('igreja_origem', models.CharField(blank=True, max_length=160, verbose_name='Igreja/ministerio de origem')),
                ('cidade', models.CharField(blank=True, max_length=120, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=80, verbose_name='Estado')),
                ('pais', models.CharField(blank=True, default='Brasil', max_length=80, verbose_name='Pais')),
                ('biografia', models.TextField(blank=True, verbose_name='Biografia/resumo')),
                ('observacoes_internas', models.TextField(blank=True, verbose_name='Observacoes internas')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='ministros/fotos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), ministros.models.validate_image_size], verbose_name='Foto principal')),
                ('tipo_chave_pix', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatoria', 'Chave aleatoria')], max_length=20, verbose_name='Tipo de chave PIX')),
                ('chave_pix', models.CharField(blank=True, max_length=180, verbose_name='Chave PIX')),
                ('qr_code_pix', models.ImageField(blank=True, null=True, upload_to='ministros/pix/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), ministros.models.validate_image_size], verbose_name='QR Code PIX')),
                ('favorecido_nome', models.CharField(blank=True, max_length=160, verbose_name='Nome do favorecido')),
                ('favorecido_documento', models.CharField(blank=True, max_length=30, verbose_name='CPF/CNPJ do favorecido')),
                ('banco', models.CharField(blank=True, max_length=120, verbose_name='Banco')),
                ('observacoes_financeiras', models.TextField(blank=True, verbose_name='Observacoes financeiras')),
                ('restricao_alimentar', models.TextField(blank=True, verbose_name='Restricao alimentar')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias')),
                ('preferencia_alimentacao', models.TextField(blank=True, verbose_name='Preferencia de alimentacao')),
                ('observacoes_hospedagem', models.TextField(blank=True, verbose_name='Observacoes de hospedagem')),
                ('observacoes_transporte', models.TextField(blank=True, verbose_name='Observacoes de transporte')),
                ('necessidades_especiais', models.TextField(blank=True, verbose_name='Necessidades especiais')),
                ('token_formulario', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token do formulario externo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Ministro',
                'verbose_name_plural': 'Ministros',
                'ordering': ['nome_ministerial', 'nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='FotoMinistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='ministros/galeria/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), ministros.models.validate_image_size], verbose_name='Imagem')),
                ('legenda', models.CharField(blank=True, max_length=180, verbose_name='Legenda')),
                ('destaque', models.BooleanField(default=False, verbose_name='Destaque')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('ministro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='ministros.ministro', verbose_name='Ministro')),
            ],
            options={
                'verbose_name': 'Foto do ministro',
                'verbose_name_plural': 'Fotos dos ministros',
                'ordering': ['-destaque', '-criado_em'],
            },
        ),
    ]
