# Generated by Django 6.0 on 2026-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('local', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(blank=True, choices=[('culto', 'Culto'), ('evento', 'Evento'), ('ensino', 'Ensino'), ('conferencia', 'Conferência'), ('reuniao', 'Reunião'), ('usina_de_forca', 'Usina de Força')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='eventos/')),
                ('publicado', models.BooleanField(default=True)),
                ('destaque_home', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['data', 'horario'],
            },
        ),
    ]
