# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("eventos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="evento",
            old_name="data",
            new_name="data_inicio",
        ),
        migrations.AddField(
            model_name="evento",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="capacidade_maxima",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="evento",
            name="inscricoes_abertas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="evento",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="evento",
            name="tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("conferencia", "Conferencia"),
                    ("seminario", "Seminario"),
                    ("encontro", "Encontro"),
                    ("treinamento", "Treinamento"),
                    ("congresso", "Congresso"),
                    ("retiro", "Retiro"),
                    ("especial", "Evento especial"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterModelOptions(
            name="evento",
            options={
                "ordering": ["data_inicio", "horario"],
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
            },
        ),
        migrations.CreateModel(
            name="InscricaoEvento",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("telefone", models.CharField(blank=True, max_length=30, verbose_name="Telefone/WhatsApp")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inscrito", "Inscrito"),
                            ("cancelado", "Cancelado"),
                            ("presente", "Presente"),
                        ],
                        default="inscrito",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "pagamento_status",
                    models.CharField(
                        blank=True,
                        help_text="Reservado para integracao futura. Nao usado agora.",
                        max_length=30,
                        verbose_name="Status de pagamento futuro",
                    ),
                ),
                ("presente_em", models.DateTimeField(blank=True, null=True, verbose_name="Presente em")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "checkin_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checkins_eventos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Check-in por",
                    ),
                ),
                (
                    "evento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscricoes",
                        to="eventos.evento",
                        verbose_name="Evento",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inscricoes_eventos",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario vinculado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Inscricao de evento",
                "verbose_name_plural": "Inscricoes de eventos",
                "ordering": ["nome"],
            },
        ),
        migrations.AddConstraint(
            model_name="inscricaoevento",
            constraint=models.UniqueConstraint(
                condition=Q(("usuario__isnull", False)),
                fields=("evento", "usuario"),
                name="uniq_inscricao_evento_por_usuario",
            ),
        ),
        migrations.AddConstraint(
            model_name="inscricaoevento",
            constraint=models.UniqueConstraint(
                fields=("evento", "email"),
                name="uniq_inscricao_evento_por_email",
            ),
        ),
    ]
