# Generated by Django 6.0.4 on 2026-05-01 21:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_gestao_inscricoes_eventos'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaoevento',
            name='checkin_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in em'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='checkin_realizado',
            field=models.BooleanField(default=False, verbose_name='Check-in realizado'),
        ),
        migrations.AddField(
            model_name='inscricaoevento',
            name='codigo_checkin',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, verbose_name='Codigo de check-in'),
        ),
    ]
