# Generated by GPT-5.2 on 2026-05-01

import uuid

from django.db import migrations


def forwards(apps, schema_editor):
    InscricaoEvento = apps.get_model("eventos", "InscricaoEvento")

    # Preenche codigo_checkin (UUID) para registros existentes.
    existentes = set(
        InscricaoEvento.objects.exclude(codigo_checkin__isnull=True).values_list("codigo_checkin", flat=True)
    )

    batch = []
    for inscricao in InscricaoEvento.objects.all().only("id", "codigo_checkin", "status", "presente_em", "checkin_em", "checkin_realizado"):
        mudou = False

        if not inscricao.codigo_checkin:
            novo = uuid.uuid4()
            while novo in existentes:
                novo = uuid.uuid4()
            existentes.add(novo)
            inscricao.codigo_checkin = novo
            mudou = True

        if inscricao.status == "presente" and not inscricao.checkin_realizado:
            inscricao.checkin_realizado = True
            mudou = True

        if not inscricao.checkin_em and inscricao.presente_em:
            inscricao.checkin_em = inscricao.presente_em
            mudou = True

        if mudou:
            batch.append(inscricao)

    if batch:
        InscricaoEvento.objects.bulk_update(batch, ["codigo_checkin", "checkin_realizado", "checkin_em"])


def backwards(apps, schema_editor):
    # Nao desfaz: manter tokens para rastreabilidade.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("eventos", "0003_inscricaoevento_checkin_em_and_more"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

