# Generated by Django 6.0.4 on 2026-05-01 21:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_preencher_codigo_checkin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaoevento',
            name='codigo_checkin',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Codigo de check-in'),
        ),
    ]
