# Generated by Django 6.0.4 on 2026-08-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('preferred_name', models.CharField(blank=True, max_length=150, verbose_name='Nome preferido')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa')], default='ACTIVE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
                'ordering': ['full_name', 'birth_date', 'id'],
                'indexes': [models.Index(fields=['full_name', 'birth_date'], name='person_name_birth_idx')],
            },
        ),
    ]
