# Generated by Django 6.0.4 on 2026-08-24 15:13

import pessoas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_personunavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pessoas.models.person_photo_upload_to, verbose_name='Foto'),
        ),
    ]
