# Generated by Django 6.0 on 2026-04-21 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_igreja', models.CharField(default='Verbo da Vida - Jardim São Paulo', max_length=120)),
                ('Logo_img', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone fixo')),
                ('whatsapp', models.CharField(blank=True, help_text='Ex: (81) 90000-0000', max_length=20, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail corporativo')),
                ('endereco', models.CharField(blank=True, help_text='Ex: R. Dr. Gustavo Pinto, 72 - Estância, Recife - PE, 50781-740', max_length=255, verbose_name='Endereço completo')),
                ('instagram', models.URLField(blank=True, help_text='Link completo do perfil', verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, help_text='Link completo da página', verbose_name='Facebook')),
                ('texto_institucional', models.TextField(blank=True, help_text="Usado no rodapé ou banners pequenos. Exemplo: 'Um lugar para crescer em fé...'", verbose_name='Texto institucional curto')),
                ('horarios_cultos', models.TextField(blank=True, help_text="Exibidos na home e footer. Coloque um por linha. Ex: 'Domingo — 19:00'", verbose_name='Horários principais')),
                ('youtube_embed_url', models.URLField(blank=True, help_text='Cole uma URL de embed do YouTube (ex: https://www.youtube.com/embed/SEU_VIDEO).', verbose_name='Link Ao Vivo (YouTube)')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do site',
                'verbose_name_plural': 'Configuração do site',
            },
        ),
        migrations.CreateModel(
            name='SobrePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_titulo', models.CharField(default='Sobre nós', max_length=120, verbose_name='Título do banner')),
                ('banner_subtitulo', models.CharField(default='Conheça nossa história, nossa missão e o propósito que nos move.', max_length=255, verbose_name='Subtítulo do banner')),
                ('historia_titulo', models.CharField(default='Nossa história', max_length=120, verbose_name='Título da seção história')),
                ('historia_texto', models.TextField(default='Nossa igreja nasceu do desejo de ver pessoas se aproximando de Deus e vivendo uma fé prática: que transforma o coração, fortalece famílias e gera propósito para o dia a dia.\n\nSomos uma comunidade acolhedora, com espaço para todas as idades, caminhando juntos em comunhão, serviço e crescimento espiritual.', help_text='Separe parágrafos com linhas em branco.', verbose_name='Texto da história')),
                ('missao', models.TextField(default='Anunciar o evangelho e formar discípulos, conectando pessoas a Deus e à comunidade, com amor e clareza.', verbose_name='Missão')),
                ('visao', models.TextField(default='Ser uma igreja relevante e acolhedora, que inspira fé, comunhão e serviço, impactando nossa cidade.', verbose_name='Visão')),
                ('valores', models.TextField(default='Bíblia como fundamento, comunhão, excelência com simplicidade, generosidade e cuidado com pessoas.', verbose_name='Valores')),
                ('horarios', models.TextField(default='Domingo — 09:00 (Culto da manhã)\nDomingo — 19:00 (Culto da noite)\nQuarta — 20:00 (Culto de ensino)', help_text='Um horário por linha. Formato livre.', verbose_name='Horários dos cultos')),
                ('endereco', models.CharField(default='R. Dr. Gustavo Pinto, 72 — Estância, Recife — PE', max_length=255, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, default='(00) 0000-0000', max_length=30, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, default='(00) 00000-0000', max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, default='contato@suaigreja.com', max_length=254, verbose_name='E-mail')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Sobre',
                'verbose_name_plural': 'Página Sobre',
            },
        ),
        migrations.CreateModel(
            name='Lider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=120, verbose_name='Cargo / função')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, help_text='Tamanho recomendado: 400×400 px.', null=True, upload_to='lideres/', verbose_name='Foto')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.', verbose_name='Ordem de exibição')),
                ('sobre_page', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lideres', to='core.sobrepage', verbose_name='Página Sobre')),
            ],
            options={
                'verbose_name': 'Líder',
                'verbose_name_plural': 'Líderes',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
