# Generated by Django 6.0.4 on 2026-04-22 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('assunto', models.CharField(blank=True, max_length=160, verbose_name='Assunto')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('respondida', models.BooleanField(default=False, verbose_name='Respondida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebida em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensagens_contato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mensagem de contato',
                'verbose_name_plural': 'Mensagens de contato',
                'ordering': ['-criado_em'],
            },
        ),
    ]
