# Generated by Django 6.0.4 on 2026-04-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contatomensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='mapa_embed_url',
            field=models.URLField(blank=True, help_text='Cole a URL usada no iframe de incorporação do Google Maps.', verbose_name='Link de incorporação do Google Maps'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='youtube_embed_url',
            field=models.URLField(blank=True, help_text='Cole uma URL do YouTube nos formatos embed, watch ou youtu.be.', verbose_name='Link Ao Vivo (YouTube)'),
        ),
    ]
