# Generated by Django 6.0.4 on 2026-04-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteconfig_mapa_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='hero_agenda',
            field=models.ImageField(blank=True, help_text='Imagem de fundo usada no topo da pagina Agenda.', null=True, upload_to='site/heroes/', verbose_name='Hero da Agenda'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_ao_vivo',
            field=models.ImageField(blank=True, help_text='Imagem de fundo usada no topo da pagina Ao Vivo.', null=True, upload_to='site/heroes/', verbose_name='Hero do Ao Vivo'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_contato',
            field=models.ImageField(blank=True, help_text='Imagem de fundo usada no topo da pagina Contato.', null=True, upload_to='site/heroes/', verbose_name='Hero do Contato'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_home',
            field=models.ImageField(blank=True, help_text='Imagem de fundo usada no topo da pagina inicial.', null=True, upload_to='site/heroes/', verbose_name='Hero da Home'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_noticias',
            field=models.ImageField(blank=True, help_text='Imagem de fundo usada no topo da pagina de noticias.', null=True, upload_to='site/heroes/', verbose_name='Hero das Noticias'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='hero_sobre',
            field=models.ImageField(blank=True, help_text='Imagem de fundo usada no topo da pagina Sobre.', null=True, upload_to='site/heroes/', verbose_name='Hero do Sobre'),
        ),
    ]
