# Generated by Codex on 2026-04-26

from django.db import migrations


def migrate_sobre_contact_data_to_siteconfig(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    SobrePage = apps.get_model("core", "SobrePage")

    sobre = SobrePage.objects.filter(pk=1).first()
    if sobre is None:
        return

    site, _ = SiteConfig.objects.get_or_create(pk=1)
    field_map = {
        "horarios": "horarios_cultos",
        "endereco": "endereco",
        "telefone": "telefone",
        "whatsapp": "whatsapp",
        "email": "email",
    }
    updated_fields = []

    for source_field, target_field in field_map.items():
        source_value = (getattr(sobre, source_field, "") or "").strip()
        target_value = (getattr(site, target_field, "") or "").strip()
        if source_value and not target_value:
            setattr(site, target_field, source_value)
            updated_fields.append(target_field)

    if updated_fields:
        site.save(update_fields=sorted(set(updated_fields)))


def restore_siteconfig_contact_data_to_sobrepage(apps, schema_editor):
    SiteConfig = apps.get_model("core", "SiteConfig")
    SobrePage = apps.get_model("core", "SobrePage")

    site = SiteConfig.objects.filter(pk=1).first()
    if site is None:
        return

    sobre, _ = SobrePage.objects.get_or_create(pk=1)
    field_map = {
        "horarios_cultos": "horarios",
        "endereco": "endereco",
        "telefone": "telefone",
        "whatsapp": "whatsapp",
        "email": "email",
    }
    updated_fields = []

    for source_field, target_field in field_map.items():
        source_value = (getattr(site, source_field, "") or "").strip()
        target_value = (getattr(sobre, target_field, "") or "").strip()
        if source_value and not target_value:
            setattr(sobre, target_field, source_value)
            updated_fields.append(target_field)

    if updated_fields:
        sobre.save(update_fields=sorted(set(updated_fields)))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_siteconfig_hero_agenda_siteconfig_hero_ao_vivo_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_sobre_contact_data_to_siteconfig,
            restore_siteconfig_contact_data_to_sobrepage,
        ),
        migrations.RemoveField(
            model_name="sobrepage",
            name="email",
        ),
        migrations.RemoveField(
            model_name="sobrepage",
            name="endereco",
        ),
        migrations.RemoveField(
            model_name="sobrepage",
            name="horarios",
        ),
        migrations.RemoveField(
            model_name="sobrepage",
            name="telefone",
        ),
        migrations.RemoveField(
            model_name="sobrepage",
            name="whatsapp",
        ),
    ]
