# Generated by Django 6.0.4 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_consolidate_sobrepage_contact_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="mapa_embed_url",
            field=models.URLField(
                blank=True,
                help_text="Cole a URL usada no iframe de incorporação do Google Maps.",
                max_length=2000,
                verbose_name="Link de incorporação do Google Maps",
            ),
        ),
    ]
