# Generated by Django 6.0.4 on 2026-09-11 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_siteconfig_mapa_embed_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=80, verbose_name='Tipo')),
                ('title', models.CharField(max_length=160, verbose_name='Titulo')),
                ('message', models.CharField(max_length=500, verbose_name='Mensagem')),
                ('target_url', models.CharField(blank=True, max_length=255, verbose_name='URL de destino')),
                ('source_app', models.CharField(blank=True, max_length=80, verbose_name='App de origem')),
                ('source_type', models.CharField(blank=True, max_length=80, verbose_name='Tipo de origem')),
                ('source_id', models.CharField(blank=True, max_length=80, verbose_name='ID de origem')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lida em')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinatario')),
            ],
            options={
                'verbose_name': 'Notificacao',
                'verbose_name_plural': 'Notificacoes',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['recipient', 'read_at'], name='notif_recipient_read_idx'), models.Index(fields=['recipient', '-created_at'], name='notif_recipient_created_idx')],
            },
        ),
    ]
