# Generated by Django 6.0.4 on 2026-05-02 16:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ministros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaVerboNoLar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='Nome da casa')),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=30, verbose_name='Telefone/WhatsApp')),
                ('endereco', models.CharField(blank=True, max_length=220, verbose_name='Endereco completo')),
                ('bairro', models.CharField(blank=True, max_length=120, verbose_name='Bairro')),
                ('ponto_referencia', models.CharField(blank=True, max_length=180, verbose_name='Ponto de referencia')),
                ('link_google_maps', models.URLField(blank=True, verbose_name='Link do Google Maps')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('dia_padrao', models.CharField(blank=True, choices=[('segunda', 'Segunda-feira'), ('terca', 'Terca-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sabado'), ('domingo', 'Domingo')], max_length=20, verbose_name='Dia padrao do encontro')),
                ('horario_padrao', models.TimeField(blank=True, null=True, verbose_name='Horario padrao')),
                ('capacidade_aproximada', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidade aproximada')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('anfitriao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casas_verbo_no_lar_anfitriao', to=settings.AUTH_USER_MODEL, verbose_name='Anfitriao')),
                ('casal_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casas_verbo_no_lar_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Casal responsavel')),
            ],
            options={
                'verbose_name': 'Casa do Verbo no Lar',
                'verbose_name_plural': 'Casas do Verbo no Lar',
                'ordering': ['-ativo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EscalaVerboNoLar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(blank=True, null=True, verbose_name='Horario')),
                ('tema', models.CharField(blank=True, max_length=180, verbose_name='Tema')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('confirmado', 'Confirmado'), ('realizado', 'Realizado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalas', to='verbo_no_lar.casaverbonolar', verbose_name='Casa')),
                ('ministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas_verbo_no_lar', to='ministros.ministro', verbose_name='Ministro')),
            ],
            options={
                'verbose_name': 'Escala do Verbo no Lar',
                'verbose_name_plural': 'Escalas do Verbo no Lar',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='MaterialApoioVerboNoLar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180, verbose_name='Titulo/Tema')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('texto_base', models.CharField(blank=True, max_length=200, verbose_name='Texto base')),
                ('conteudo', models.TextField(blank=True, verbose_name='Conteudo')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='verbo_no_lar/materiais/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'ppt', 'pptx', 'txt'])], verbose_name='Anexo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('casa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiais', to='verbo_no_lar.casaverbonolar', verbose_name='Casa (opcional)')),
            ],
            options={
                'verbose_name': 'Material de apoio (Verbo no Lar)',
                'verbose_name_plural': 'Materiais de apoio (Verbo no Lar)',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RelatorioEncontroVerboNoLar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('tema', models.CharField(blank=True, max_length=180, verbose_name='Tema')),
                ('quantidade_presentes', models.PositiveIntegerField(default=0, verbose_name='Quantidade de presentes')),
                ('quantidade_visitantes', models.PositiveIntegerField(default=0, verbose_name='Quantidade de visitantes')),
                ('pedidos_oracao', models.TextField(blank=True, verbose_name='Pedidos de oracao')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='verbo_no_lar.casaverbonolar', verbose_name='Casa')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_verbo_no_lar', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('ministro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relatorios_verbo_no_lar', to='ministros.ministro', verbose_name='Ministro')),
            ],
            options={
                'verbose_name': 'Relatorio de encontro (Verbo no Lar)',
                'verbose_name_plural': 'Relatorios de encontros (Verbo no Lar)',
                'ordering': ['-data', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteVerboNoLar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_visitante', models.CharField(blank=True, max_length=160, verbose_name='Nome do visitante')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('tipo', models.CharField(choices=[('membro', 'Membro'), ('visitante', 'Visitante')], max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='verbo_no_lar.casaverbonolar', verbose_name='Casa')),
                ('membro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_verbo_no_lar', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Participante do Verbo no Lar',
                'verbose_name_plural': 'Participantes do Verbo no Lar',
                'ordering': ['-ativo', 'tipo', 'nome_visitante'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('membro__isnull', False)), fields=('casa', 'membro'), name='uniq_participante_por_membro_e_casa')],
            },
        ),
    ]
