# Generated by Django 6.0 on 2026-04-21 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, help_text='URL amigável da notícia. Caso deixe em branco, será gerado automaticamente.', max_length=200, unique=True, verbose_name='Slug')),
                ('resumo', models.TextField(blank=True, help_text='Texto curto exibido nos cards (na listagem e na home).', verbose_name='Resumo')),
                ('conteudo', models.TextField(help_text='Suporta HTML/Markdown se integrado no frontend.', verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='noticias/', verbose_name='Imagem')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('destaque_home', models.BooleanField(default=False, help_text='Marque para aparecer na seção Últimas Notícias da homepage.', verbose_name='Destaque na Home')),
                ('data_publicacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data da publicação')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data_publicacao', '-criado_em'],
            },
        ),
    ]
