# Generated by Django 6.0.4 on 2026-04-26 00:00

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departamentos", "0004_departamento_codigo"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="IndisponibilidadeMembro",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("data_inicio", models.DateField(verbose_name="Data inicial")),
                        ("data_fim", models.DateField(verbose_name="Data final")),
                        ("horario_inicio", models.TimeField(blank=True, null=True, verbose_name="Horario inicial")),
                        ("horario_fim", models.TimeField(blank=True, null=True, verbose_name="Horario final")),
                        ("motivo", models.TextField(blank=True, verbose_name="Motivo")),
                        ("ativo", models.BooleanField(default=True, verbose_name="Ativa")),
                        ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                        ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                        (
                            "membro",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="indisponibilidades_escala",
                                to=settings.AUTH_USER_MODEL,
                                verbose_name="Membro",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Indisponibilidade do membro",
                        "verbose_name_plural": "Indisponibilidades dos membros",
                        "ordering": ["-data_inicio", "-horario_inicio", "-criado_em"],
                        "db_table": "departamentos_indisponibilidademembro",
                    },
                ),
                migrations.CreateModel(
                    name="CultoPadrao",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("nome", models.CharField(max_length=120, unique=True, verbose_name="Nome do culto")),
                        ("dia_semana", models.PositiveSmallIntegerField(choices=[(0, "Segunda-feira"), (1, "Terca-feira"), (2, "Quarta-feira"), (3, "Quinta-feira"), (4, "Sexta-feira"), (5, "Sabado"), (6, "Domingo")], verbose_name="Dia da semana")),
                        ("horario", models.TimeField(verbose_name="Horario")),
                        ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                        ("observacoes", models.TextField(blank=True, verbose_name="Observacoes")),
                        ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                        ("atualizado_em", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                    ],
                    options={
                        "verbose_name": "Culto padrao",
                        "verbose_name_plural": "Cultos padrao",
                        "ordering": ["dia_semana", "horario", "nome"],
                        "db_table": "departamentos_cultopadrao",
                        "constraints": [
                            models.UniqueConstraint(
                                condition=models.Q(("ativo", True)),
                                fields=("dia_semana", "horario"),
                                name="uniq_culto_padrao_ativo_por_dia_horario",
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="Escala",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("titulo", models.CharField(max_length=150, verbose_name="Titulo")),
                        ("data", models.DateField(verbose_name="Data")),
                        ("horario", models.TimeField(verbose_name="Horario")),
                        ("observacoes", models.TextField(blank=True, verbose_name="Observacoes")),
                        ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                        ("criada_em", models.DateTimeField(auto_now_add=True, verbose_name="Criada em")),
                        (
                            "culto_padrao",
                            models.ForeignKey(
                                blank=True,
                                null=True,
                                on_delete=django.db.models.deletion.SET_NULL,
                                related_name="escalas",
                                to="escalas.cultopadrao",
                                verbose_name="Culto padrao",
                            ),
                        ),
                        (
                            "departamento",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="escalas",
                                to="departamentos.departamento",
                                verbose_name="Departamento",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Escala",
                        "verbose_name_plural": "Escalas",
                        "ordering": ["data", "horario", "titulo"],
                        "db_table": "departamentos_escala",
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("departamento", "data", "horario"),
                                name="uniq_escala_por_departamento_data_horario",
                            )
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="EscalaItem",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("funcao", models.CharField(max_length=120, verbose_name="Funcao na escala")),
                        ("confirmado", models.BooleanField(default=False, verbose_name="Confirmado")),
                        ("observacoes", models.TextField(blank=True, verbose_name="Observacoes")),
                        ("criado_em", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                        (
                            "escala",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="itens",
                                to="escalas.escala",
                                verbose_name="Escala",
                            ),
                        ),
                        (
                            "participacao",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.PROTECT,
                                related_name="itens_escala",
                                to="departamentos.departamentomembro",
                                verbose_name="Membro escalado",
                            ),
                        ),
                    ],
                    options={
                        "verbose_name": "Item da escala",
                        "verbose_name_plural": "Itens da escala",
                        "ordering": ["escala__data", "escala__horario", "funcao", "participacao__membro__first_name"],
                        "db_table": "departamentos_escalaitem",
                        "constraints": [
                            models.UniqueConstraint(
                                fields=("escala", "participacao"),
                                name="uniq_participacao_por_escala",
                            )
                        ],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
