# Generated by Django 6.0.4 on 2026-04-23 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConteudoAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID do objeto')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objeto')),
                ('acao', models.CharField(choices=[('create', 'Criacao'), ('update', 'Atualizacao'), ('delete', 'Exclusao'), ('publish', 'Publicacao'), ('unpublish', 'Despublicacao')], max_length=20, verbose_name='Acao')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='Campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='Valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='Valor novo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias_conteudo_publico', to='contenttypes.contenttype', verbose_name='Tipo de conteudo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_conteudo_publico', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de auditoria',
                'verbose_name_plural': 'Logs de auditoria',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
