# Generated by Django 6.0.4 on 2026-09-15 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaconia', '0007_inventory_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data')),
                ('notes', models.TextField(blank=True, verbose_name='Observacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diaconia_inventory_counts', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Contagem de inventario',
                'verbose_name_plural': 'Contagens de inventario',
                'ordering': ['-date', '-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantidade')),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='diaconia.inventorycount', verbose_name='Contagem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_entries', to='diaconia.inventoryitem', verbose_name='Item')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_count_entries', to='diaconia.inventorylocation', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Item da contagem de inventario',
                'verbose_name_plural': 'Itens da contagem de inventario',
                'ordering': ['item__category__name', 'item__name', 'location__name', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='inventorycount',
            index=models.Index(fields=['date'], name='diaconia_inv_count_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorycount',
            constraint=models.UniqueConstraint(fields=('date',), name='uniq_diaconia_inventory_count_date'),
        ),
        migrations.AddIndex(
            model_name='inventorycountentry',
            index=models.Index(fields=['inventory_count', 'item'], name='diac_inv_ent_count_item_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorycountentry',
            index=models.Index(fields=['inventory_count', 'location'], name='diac_inv_ent_count_loc_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountentry',
            constraint=models.UniqueConstraint(fields=('inventory_count', 'item', 'location'), name='uniq_diaconia_inventory_count_item_location'),
        ),
        migrations.AddConstraint(
            model_name='inventorycountentry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_diaconia_inventory_entry_quantity_gte_0'),
        ),
    ]
