SCHEDULE_PUBLISHED = "SCHEDULE_PUBLISHED"
SCHEDULE_ASSIGNMENT_ADDED = "SCHEDULE_ASSIGNMENT_ADDED"
SCHEDULE_ASSIGNMENT_REMOVED = "SCHEDULE_ASSIGNMENT_REMOVED"
SCHEDULE_CANCELLED = "SCHEDULE_CANCELLED"

SCHEDULE_NOTIFICATION_TYPES = {
    SCHEDULE_PUBLISHED,
    SCHEDULE_ASSIGNMENT_ADDED,
    SCHEDULE_ASSIGNMENT_REMOVED,
    SCHEDULE_CANCELLED,
}
