# Generated by Django 6.0.4 on 2026-08-19 23:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data de entrada na jornada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='church_journey', to='pessoas.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Jornada eclesiastica',
                'verbose_name_plural': 'Jornadas eclesiasticas',
                'ordering': ['person__full_name', 'person_id'],
            },
        ),
    ]
