# Generated by Django 6.0.4 on 2026-08-20 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_journey', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da turma')),
                ('start_date', models.DateField(verbose_name='Data de inicio')),
                ('expected_end_date', models.DateField(verbose_name='Termino previsto')),
                ('planned_sessions', models.PositiveIntegerField(verbose_name='Quantidade prevista de aulas')),
                ('status', models.CharField(choices=[('PLANNED', 'Planejada'), ('IN_PROGRESS', 'Em andamento'), ('COMPLETED', 'Concluida'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipleship_classes_taught', to='pessoas.person', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Turma de discipulado',
                'verbose_name_plural': 'Turmas de discipulado',
                'ordering': ['-start_date', 'name', 'id'],
                'permissions': [('start_discipleshipclass', 'Can start discipleship class'), ('complete_discipleshipclass', 'Can complete discipleship class'), ('cancel_discipleshipclass', 'Can cancel discipleship class')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'IN_PROGRESS')), fields=('status',), name='unique_discipleship_class_in_progress')],
            },
        ),
    ]
