# Generated by Django 6.0.4 on 2026-08-20 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_journey', '0002_discipleshipclass'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Matriculado'), ('WITHDRAWN', 'Desistente')], default='ENROLLED', max_length=20, verbose_name='Status')),
                ('enrolled_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da matricula')),
                ('withdrawn_at', models.DateField(blank=True, null=True, verbose_name='Data da desistencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('discipleship_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='church_journey.discipleshipclass', verbose_name='Turma de discipulado')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipleship_enrollments', to='pessoas.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Matricula de discipulado',
                'verbose_name_plural': 'Matriculas de discipulado',
                'ordering': ['person__full_name', 'id'],
                'permissions': [('withdraw_discipleshipenrollment', 'Can withdraw discipleship enrollment')],
                'constraints': [models.UniqueConstraint(fields=('person', 'discipleship_class'), name='unique_person_discipleship_class_enrollment')],
            },
        ),
    ]
