# Generated by Django 6.0.4 on 2026-08-20 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_journey', '0003_discipleshipenrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('lesson_date', models.DateField(verbose_name='Data da aula')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendada'), ('CANCELLED', 'Cancelada')], default='SCHEDULED', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('discipleship_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='church_journey.discipleshipclass', verbose_name='Turma de discipulado')),
            ],
            options={
                'verbose_name': 'Aula de discipulado',
                'verbose_name_plural': 'Aulas de discipulado',
                'ordering': ['lesson_date', 'id'],
                'permissions': [('cancel_discipleshiplesson', 'Can cancel discipleship lesson')],
                'constraints': [models.UniqueConstraint(fields=('discipleship_class', 'lesson_date'), name='unique_discipleship_class_lesson_date')],
            },
        ),
    ]
