# Generated by Django 6.0.4 on 2026-08-20 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_journey', '0004_discipleshiplesson'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscipleshipAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('JUSTIFIED', 'Justificada')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='church_journey.discipleshipenrollment', verbose_name='Matricula')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='church_journey.discipleshiplesson', verbose_name='Aula')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discipleship_attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Presenca de discipulado',
                'verbose_name_plural': 'Presencas de discipulado',
                'ordering': ['lesson__lesson_date', 'enrollment__person__full_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'lesson'), name='unique_discipleship_attendance_enrollment_lesson')],
            },
        ),
        migrations.CreateModel(
            name='DiscipleshipClassAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('discipleship_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='church_journey.discipleshipclass', verbose_name='Turma de discipulado')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discipleship_classes_assisted', to='pessoas.person', verbose_name='Auxiliar')),
            ],
            options={
                'verbose_name': 'Auxiliar de turma de discipulado',
                'verbose_name_plural': 'Auxiliares de turmas de discipulado',
                'ordering': ['person__full_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('discipleship_class', 'person'), name='unique_discipleship_class_assistant')],
            },
        ),
    ]
