# Generated by Django 6.0.4 on 2026-08-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_journey', '0005_discipleshipattendance_discipleshipclassassistant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipleshipenrollment',
            options={'ordering': ['person__full_name', 'id'], 'permissions': [('withdraw_discipleshipenrollment', 'Can withdraw discipleship enrollment'), ('complete_discipleshipenrollment', 'Can complete discipleship enrollment')], 'verbose_name': 'Matricula de discipulado', 'verbose_name_plural': 'Matriculas de discipulado'},
        ),
        migrations.AddField(
            model_name='discipleshipenrollment',
            name='completed_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusao'),
        ),
        migrations.AlterField(
            model_name='discipleshipenrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Matriculado'), ('WITHDRAWN', 'Desistente'), ('COMPLETED', 'Concluido')], default='ENROLLED', max_length=20, verbose_name='Status'),
        ),
    ]
