# Generated by Codex on 2026-08-22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("church_journey", "0006_alter_discipleshipenrollment_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativa"), ("INACTIVE", "Inativa")],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("member_since", models.DateField(verbose_name="Membro desde")),
                ("approved_at", models.DateTimeField(blank=True, null=True, verbose_name="Aprovado em")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Criado em")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Atualizado em")),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="memberships_approved",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprovado por",
                    ),
                ),
                (
                    "person",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="membership",
                        to="pessoas.person",
                        verbose_name="Pessoa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Membresia",
                "verbose_name_plural": "Membresias",
                "ordering": ["person__full_name", "person_id"],
            },
        ),
    ]
