# Generated by Codex on 2026-08-22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("church_journey", "0007_membership"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "ordering": ["person__full_name", "person_id"],
                "permissions": [
                    ("approve_membership", "Can approve membership"),
                    ("deactivate_membership", "Can deactivate membership"),
                    ("reactivate_membership", "Can reactivate membership"),
                ],
                "verbose_name": "Membresia",
                "verbose_name_plural": "Membresias",
            },
        ),
        migrations.CreateModel(
            name="MembershipStatusHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "from_status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativa"), ("INACTIVE", "Inativa")],
                        max_length=20,
                        verbose_name="Status anterior",
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativa"), ("INACTIVE", "Inativa")],
                        max_length=20,
                        verbose_name="Novo status",
                    ),
                ),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Alterado em")),
                ("reason", models.TextField(blank=True, verbose_name="Motivo/observacao")),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="membership_status_changes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alterado por",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="church_journey.membership",
                        verbose_name="Membresia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historico de status de membresia",
                "verbose_name_plural": "Historicos de status de membresia",
                "ordering": ["-changed_at", "-id"],
            },
        ),
    ]
