from django.urls import path

from . import api_views


urlpatterns = [
    path(
        "inventory/counts/",
        api_views.InventoryCountListCreateView.as_view(),
        name="diaconia-inventory-count-list",
    ),
    path(
        "inventory/counts/<int:pk>/",
        api_views.InventoryCountDetailView.as_view(),
        name="diaconia-inventory-count-detail",
    ),
    path(
        "inventory/counts/<int:pk>/comparison/",
        api_views.InventoryCountComparisonView.as_view(),
        name="diaconia-inventory-count-comparison",
    ),
    path(
        "inventory/items/",
        api_views.InventoryItemListCreateView.as_view(),
        name="diaconia-inventory-item-list",
    ),
    path(
        "inventory/items/<int:pk>/",
        api_views.InventoryItemDetailView.as_view(),
        name="diaconia-inventory-item-detail",
    ),
    path(
        "inventory/items/<int:pk>/deactivate/",
        api_views.InventoryItemDeactivateView.as_view(),
        name="diaconia-inventory-item-deactivate",
    ),
    path(
        "inventory/items/<int:pk>/reactivate/",
        api_views.InventoryItemReactivateView.as_view(),
        name="diaconia-inventory-item-reactivate",
    ),
    path(
        "inventory/categories/",
        api_views.InventoryCategoryListCreateView.as_view(),
        name="diaconia-inventory-category-list",
    ),
    path(
        "inventory/categories/<int:pk>/",
        api_views.InventoryCategoryDetailView.as_view(),
        name="diaconia-inventory-category-detail",
    ),
    path(
        "inventory/categories/<int:pk>/deactivate/",
        api_views.InventoryCategoryDeactivateView.as_view(),
        name="diaconia-inventory-category-deactivate",
    ),
    path(
        "inventory/categories/<int:pk>/reactivate/",
        api_views.InventoryCategoryReactivateView.as_view(),
        name="diaconia-inventory-category-reactivate",
    ),
    path(
        "inventory/locations/",
        api_views.InventoryLocationListCreateView.as_view(),
        name="diaconia-inventory-location-list",
    ),
    path(
        "inventory/locations/<int:pk>/",
        api_views.InventoryLocationDetailView.as_view(),
        name="diaconia-inventory-location-detail",
    ),
    path(
        "inventory/locations/<int:pk>/deactivate/",
        api_views.InventoryLocationDeactivateView.as_view(),
        name="diaconia-inventory-location-deactivate",
    ),
    path(
        "inventory/locations/<int:pk>/reactivate/",
        api_views.InventoryLocationReactivateView.as_view(),
        name="diaconia-inventory-location-reactivate",
    ),
    path(
        "counting/counts/",
        api_views.AttendanceCountListCreateView.as_view(),
        name="diaconia-attendance-count-list",
    ),
    path(
        "counting/counts/<int:pk>/",
        api_views.AttendanceCountDetailView.as_view(),
        name="diaconia-attendance-count-detail",
    ),
    path(
        "counting/environments/",
        api_views.CountingEnvironmentListCreateView.as_view(),
        name="diaconia-counting-environment-list",
    ),
    path(
        "counting/environments/<int:pk>/",
        api_views.CountingEnvironmentDetailView.as_view(),
        name="diaconia-counting-environment-detail",
    ),
    path(
        "counting/environments/<int:pk>/deactivate/",
        api_views.CountingEnvironmentDeactivateView.as_view(),
        name="diaconia-counting-environment-deactivate",
    ),
    path(
        "counting/environments/<int:pk>/reactivate/",
        api_views.CountingEnvironmentReactivateView.as_view(),
        name="diaconia-counting-environment-reactivate",
    ),
    path("stock/summary/", api_views.StockSummaryView.as_view(), name="diaconia-stock-summary"),
    path("stock/units/", api_views.StockUnitListView.as_view(), name="diaconia-stock-unit-list"),
    path("stock/categories/", api_views.StockCategoryListCreateView.as_view(), name="diaconia-stock-category-list"),
    path("stock/categories/<int:pk>/", api_views.StockCategoryDetailView.as_view(), name="diaconia-stock-category-detail"),
    path(
        "stock/categories/<int:pk>/deactivate/",
        api_views.StockCategoryDeactivateView.as_view(),
        name="diaconia-stock-category-deactivate",
    ),
    path(
        "stock/categories/<int:pk>/reactivate/",
        api_views.StockCategoryReactivateView.as_view(),
        name="diaconia-stock-category-reactivate",
    ),
    path("stock/items/", api_views.StockItemListCreateView.as_view(), name="diaconia-stock-item-list"),
    path("stock/items/<int:pk>/", api_views.StockItemDetailView.as_view(), name="diaconia-stock-item-detail"),
    path(
        "stock/items/<int:pk>/deactivate/",
        api_views.StockItemDeactivateView.as_view(),
        name="diaconia-stock-item-deactivate",
    ),
    path(
        "stock/items/<int:pk>/reactivate/",
        api_views.StockItemReactivateView.as_view(),
        name="diaconia-stock-item-reactivate",
    ),
    path("stock/movements/", api_views.StockMovementListCreateView.as_view(), name="diaconia-stock-movement-list"),
    path(
        "stock/movements/<int:pk>/",
        api_views.StockMovementDetailView.as_view(),
        name="diaconia-stock-movement-detail",
    ),
]
