# Generated by Django 6.0.4 on 2026-05-05 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_status_eclesiastico(apps, schema_editor):
    Usuario = apps.get_model("usuarios", "Usuario")
    Usuario.objects.filter(is_membro=True).update(
        status_eclesiastico="membro",
        discipulado_concluido=True,
    )
    Usuario.objects.filter(is_membro=False).update(status_eclesiastico="visitante")


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='discipulado_concluido',
            field=models.BooleanField(default=False, verbose_name='Discipulado concluido?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='discipulado_concluido_em',
            field=models.DateField(blank=True, null=True, verbose_name='Data de conclusao do discipulado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='eh_pastor',
            field=models.BooleanField(default=False, verbose_name='Pastor?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='qualificado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Qualificado em'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='qualificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_qualificados', to=settings.AUTH_USER_MODEL, verbose_name='Qualificado por'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='status_eclesiastico',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('membro', 'Membro')], default='visitante', max_length=20, verbose_name='Status eclesiastico'),
        ),
        migrations.RunPython(migrar_status_eclesiastico, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='usuario',
            name='is_membro',
        ),
    ]
