# Generated by Django 6.0.4 on 2026-08-19 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('usuarios', '0002_remove_usuario_is_membro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='person',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_account', to='pessoas.person', verbose_name='Pessoa vinculada'),
        ),
    ]
