# Generated by Django 6.0.4 on 2026-08-19 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
        ('usuarios', '0003_usuario_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=30, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=20, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Revisada em')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Motivo da rejeicao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizada em')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests', to='pessoas.person', verbose_name='Pessoa vinculada')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Revisada por')),
            ],
            options={
                'verbose_name': 'Solicitacao de acesso',
                'verbose_name_plural': 'Solicitacoes de acesso',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'email'], name='access_req_status_email_idx'), models.Index(fields=['status', 'phone'], name='access_req_status_phone_idx')],
            },
        ),
    ]
