# Generated by Django 6.0.4 on 2026-08-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_accessrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessrequest',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('approve_accessrequest', 'Can approve access request'), ('reject_accessrequest', 'Can reject access request')], 'verbose_name': 'Solicitacao de acesso', 'verbose_name_plural': 'Solicitacoes de acesso'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('disable_usuario', 'Can disable usuario access'), ('enable_usuario', 'Can enable usuario access')], 'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
