# Generated by Codex on 2026-08-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usuarios", "0005_alter_accessrequest_options_alter_usuario_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="usuario",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="access_request",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario pendente",
            ),
        ),
    ]
