from django.urls import path

from .views import (
    DiscipleshipClassDetailView,
    DiscipleshipClassLifecycleView,
    DiscipleshipClassListCreateView,
    DiscipleshipEnrollmentDetailView,
    DiscipleshipEnrollmentListCreateView,
    DiscipleshipEnrollmentWithdrawView,
    DiscipleshipLessonAttendanceView,
    DiscipleshipLessonCancelView,
    DiscipleshipLessonDetailView,
    DiscipleshipLessonListCreateView,
    PersonChurchJourneyView,
)


urlpatterns = [
    path(
        "people/<int:person_id>/church-journey/",
        PersonChurchJourneyView.as_view(),
        name="person-church-journey",
    ),
    path(
        "discipleship/classes/",
        DiscipleshipClassListCreateView.as_view(),
        name="discipleship-class-list",
    ),
    path(
        "discipleship/classes/<int:pk>/",
        DiscipleshipClassDetailView.as_view(),
        name="discipleship-class-detail",
    ),
    path(
        "discipleship/classes/<int:pk>/start/",
        DiscipleshipClassLifecycleView.as_view(
            action="start",
            permission_required="church_journey.start_discipleshipclass",
        ),
        name="discipleship-class-start",
    ),
    path(
        "discipleship/classes/<int:pk>/complete/",
        DiscipleshipClassLifecycleView.as_view(
            action="complete",
            permission_required="church_journey.complete_discipleshipclass",
        ),
        name="discipleship-class-complete",
    ),
    path(
        "discipleship/classes/<int:pk>/cancel/",
        DiscipleshipClassLifecycleView.as_view(
            action="cancel",
            permission_required="church_journey.cancel_discipleshipclass",
        ),
        name="discipleship-class-cancel",
    ),
    path(
        "discipleship/classes/<int:class_id>/enrollments/",
        DiscipleshipEnrollmentListCreateView.as_view(),
        name="discipleship-enrollment-list",
    ),
    path(
        "discipleship/classes/<int:class_id>/enrollments/<int:pk>/",
        DiscipleshipEnrollmentDetailView.as_view(),
        name="discipleship-enrollment-detail",
    ),
    path(
        "discipleship/classes/<int:class_id>/enrollments/<int:pk>/withdraw/",
        DiscipleshipEnrollmentWithdrawView.as_view(),
        name="discipleship-enrollment-withdraw",
    ),
    path(
        "discipleship/classes/<int:class_id>/lessons/",
        DiscipleshipLessonListCreateView.as_view(),
        name="discipleship-lesson-list",
    ),
    path(
        "discipleship/classes/<int:class_id>/lessons/<int:pk>/",
        DiscipleshipLessonDetailView.as_view(),
        name="discipleship-lesson-detail",
    ),
    path(
        "discipleship/classes/<int:class_id>/lessons/<int:pk>/cancel/",
        DiscipleshipLessonCancelView.as_view(),
        name="discipleship-lesson-cancel",
    ),
    path(
        "discipleship/classes/<int:class_id>/lessons/<int:lesson_id>/attendance/",
        DiscipleshipLessonAttendanceView.as_view(),
        name="discipleship-lesson-attendance",
    ),
]
