# Generated by Django 6.0.4 on 2026-05-05 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambiente', models.CharField(choices=[('teste', 'Teste'), ('producao', 'Producao')], default='teste', max_length=20, verbose_name='ambiente')),
                ('mercado_pago_access_token', models.CharField(blank=True, max_length=255, verbose_name='access token do Mercado Pago')),
                ('mercado_pago_public_key', models.CharField(blank=True, max_length=255, verbose_name='public key do Mercado Pago')),
                ('mercado_pago_webhook_secret', models.CharField(blank=True, help_text='Chave secreta usada para validar o header x-signature do webhook.', max_length=255, verbose_name='segredo do webhook Mercado Pago')),
                ('webhook_url', models.URLField(blank=True, verbose_name='URL do webhook')),
                ('conectado', models.BooleanField(default=False, verbose_name='conectado')),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True, verbose_name='ultima verificacao')),
                ('mensagem_status', models.TextField(blank=True, verbose_name='mensagem de status')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'configuracao financeira',
                'verbose_name_plural': 'configuracoes financeiras',
            },
        ),
        migrations.CreateModel(
            name='Contribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('dizimo', 'Dizimo'), ('oferta', 'Oferta'), ('missoes', 'Missoes'), ('campanha', 'Campanha')], max_length=20, verbose_name='tipo')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor')),
                ('descricao', models.TextField(blank=True, verbose_name='descricao')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('recusado', 'Recusado'), ('cancelado', 'Cancelado'), ('erro', 'Erro')], default='pendente', max_length=20, verbose_name='status')),
                ('mercado_pago_preference_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='preference id Mercado Pago')),
                ('mercado_pago_payment_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='payment id Mercado Pago')),
                ('link_pagamento', models.URLField(blank=True, max_length=500, verbose_name='link de pagamento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribuicoes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'contribuicao',
                'verbose_name_plural': 'contribuicoes',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
