# Generated by Django 6.0.4 on 2026-04-23 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DepartamentoMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('lider', 'Lider'), ('vice_lider', 'Vice-lider'), ('membro', 'Membro'), ('voluntario', 'Voluntario')], default='membro', max_length=20, verbose_name='Papel no departamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_entrada', models.DateField(blank=True, null=True, verbose_name='Data de entrada')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='departamentos.departamento', verbose_name='Departamento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participacoes_departamentais', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Membro do departamento',
                'verbose_name_plural': 'Membros do departamento',
                'ordering': ['departamento__nome', 'membro__first_name', 'membro__username'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='membros',
            field=models.ManyToManyField(blank=True, related_name='departamentos', through='departamentos.DepartamentoMembro', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Titulo')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criada_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escalas', to='departamentos.departamento', verbose_name='Departamento')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['data', 'horario', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='EscalaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=120, verbose_name='Funcao na escala')),
                ('confirmado', models.BooleanField(default=False, verbose_name='Confirmado')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='departamentos.escala', verbose_name='Escala')),
                ('participacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_escala', to='departamentos.departamentomembro', verbose_name='Membro escalado')),
            ],
            options={
                'verbose_name': 'Item da escala',
                'verbose_name_plural': 'Itens da escala',
                'ordering': ['escala__data', 'escala__horario', 'funcao', 'participacao__membro__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='departamentomembro',
            constraint=models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('membro', 'departamento'), name='uniq_participacao_ativa_por_departamento'),
        ),
        migrations.AddConstraint(
            model_name='escalaitem',
            constraint=models.UniqueConstraint(fields=('escala', 'participacao'), name='uniq_participacao_por_escala'),
        ),
    ]
