# Generated by Django 6.0.4 on 2026-04-24 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndisponibilidadeMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(verbose_name='Data inicial')),
                ('data_fim', models.DateField(verbose_name='Data final')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horario inicial')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horario final')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indisponibilidades_escala', to=settings.AUTH_USER_MODEL, verbose_name='Membro')),
            ],
            options={
                'verbose_name': 'Indisponibilidade do membro',
                'verbose_name_plural': 'Indisponibilidades dos membros',
                'ordering': ['-data_inicio', '-horario_inicio', '-criado_em'],
            },
        ),
    ]
