# Generated by Django 6.0.4 on 2026-04-25 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_indisponibilidademembro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultoPadrao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True, verbose_name='Nome do culto')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terca-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='Dia da semana')),
                ('horario', models.TimeField(verbose_name='Horario')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observacoes')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Culto padrao',
                'verbose_name_plural': 'Cultos padrao',
                'ordering': ['dia_semana', 'horario', 'nome'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('dia_semana', 'horario'), name='uniq_culto_padrao_ativo_por_dia_horario')],
            },
        ),
        migrations.AddField(
            model_name='escala',
            name='culto_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalas', to='departamentos.cultopadrao', verbose_name='Culto padrao'),
        ),
        migrations.AddConstraint(
            model_name='escala',
            constraint=models.UniqueConstraint(fields=('departamento', 'data', 'horario'), name='uniq_escala_por_departamento_data_horario'),
        ),
    ]
