# Generated by Django 6.0.4 on 2026-04-26 00:00

from django.db import migrations, models
from django.utils.text import slugify


CODIGO_PADRAO_MAP = {
    "secretaria": "secretaria",
    "departamento-de-secretaria": "secretaria",
    "midia": "midia",
    "departamento-de-midia": "midia",
    "infantil": "infantil",
    "departamento-infantil": "infantil",
}


def _gerar_codigo_unico(Departamento, instance):
    base_codigo = slugify((instance.codigo or "").strip()) or CODIGO_PADRAO_MAP.get(
        slugify((instance.nome or "").strip()),
        slugify((instance.nome or "").strip()),
    )
    if not base_codigo:
        base_codigo = "departamento"

    codigo = base_codigo
    contador = 2
    while Departamento.objects.filter(codigo=codigo).exclude(pk=instance.pk).exists():
        codigo = f"{base_codigo}-{contador}"
        contador += 1
    return codigo


def popular_codigos_departamento(apps, schema_editor):
    Departamento = apps.get_model("departamentos", "Departamento")

    for departamento in Departamento.objects.order_by("id"):
        departamento.codigo = _gerar_codigo_unico(Departamento, departamento)
        departamento.save(update_fields=["codigo"])


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0003_cultopadrao_escala_culto_padrao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="departamento",
            name="codigo",
            field=models.SlugField(
                blank=True,
                default="",
                help_text=(
                    "Identificador interno estavel usado por permissoes e integracoes. "
                    "Se ficar vazio, o sistema gera automaticamente."
                ),
                max_length=60,
                verbose_name="Codigo interno",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(popular_codigos_departamento, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="departamento",
            name="codigo",
            field=models.SlugField(
                blank=True,
                help_text=(
                    "Identificador interno estavel usado por permissoes e integracoes. "
                    "Se ficar vazio, o sistema gera automaticamente."
                ),
                max_length=60,
                unique=True,
                verbose_name="Codigo interno",
            ),
        ),
    ]
