# Generated by Django 6.0.4 on 2026-04-26 00:00

from django.db import migrations


MODELOS_ESCALAS = (
    "cultopadrao",
    "escala",
    "escalaitem",
    "indisponibilidademembro",
)


def migrar_contenttypes_para_escalas(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(
        app_label="departamentos",
        model__in=MODELOS_ESCALAS,
    ).update(app_label="escalas")


def restaurar_contenttypes_para_departamentos(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(
        app_label="escalas",
        model__in=MODELOS_ESCALAS,
    ).update(app_label="departamentos")


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("departamentos", "0004_departamento_codigo"),
        ("escalas", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(name="EscalaItem"),
                migrations.DeleteModel(name="Escala"),
                migrations.DeleteModel(name="CultoPadrao"),
                migrations.DeleteModel(name="IndisponibilidadeMembro"),
            ],
            database_operations=[],
        ),
        migrations.RunPython(
            migrar_contenttypes_para_escalas,
            restaurar_contenttypes_para_departamentos,
        ),
    ]
