# Generated by Django 6.0.4 on 2026-05-05 16:44

from django.db import migrations, models


def migrar_membro_para_liderado(apps, schema_editor):
    DepartamentoMembro = apps.get_model("departamentos", "DepartamentoMembro")
    DepartamentoMembro.objects.filter(papel="membro").update(papel="liderado")


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0005_move_scale_models_to_escalas'),
    ]

    operations = [
        migrations.RunPython(migrar_membro_para_liderado, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='departamentomembro',
            name='papel',
            field=models.CharField(choices=[('lider', 'Lider'), ('vice_lider', 'Vice-lider'), ('liderado', 'Liderado'), ('auxiliar', 'Auxiliar'), ('voluntario', 'Voluntario'), ('membro', 'Membro (legado)')], default='liderado', max_length=20, verbose_name='Papel no departamento'),
        ),
    ]
