# Generated by Codex on 2026-08-23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departamentos", "0006_alter_departamentomembro_papel"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="departamento",
            options={
                "ordering": ["nome"],
                "permissions": [
                    ("deactivate_departamento", "Can deactivate departamento"),
                    ("reactivate_departamento", "Can reactivate departamento"),
                ],
                "verbose_name": "Departamento",
                "verbose_name_plural": "Departamentos",
            },
        ),
    ]
